"""Subclass of CalFrame, which is generated by wxFormBuilder."""

import wx
import pyperclip
import need.ui_zaobiao
from need.common import *

# Implementing CalFrame
class loadCalFrame( need.ui_zaobiao.CalFrame ):
    def __init__( self, parent ):
        need.ui_zaobiao.CalFrame.__init__( self, parent )
        self.index = 1
        self.collect = []   # 用于收集计算结果
        self.floCharge = 0

    # Handlers for CalFrame events.
    def OnExit( self, event ):
        self.Close()

    def OnGoalEnter( self, event ):
        if self.m_textCtrl2.GetValidator().Validate():
            self.floGoal = float(self.m_textCtrl2.GetValue())
            if self.floGoal>0:
                if self.m_comboBox1.GetSelection()==0:
                    self.type = '货物招标'
                    cal_dict = RATE_GOODS
                elif self.m_comboBox1.GetSelection()==1:
                    self.type = '服务招标'
                    cal_dict = RATE_SERVICE
                else:
                    self.type = '工程招标'
                    cal_dict = RATE_ENGINEERING
                for key,value in cal_dict.items():
                    if self.floGoal>key:
                        self.floCharge = round(((self.floGoal-key)*value[1]+value[0])*10000,2)
                        break
                self.m_staticText10.Label = '按标准计算：%s元' % self.floCharge
            else:
                wx.MessageBox('请填写中标金额！', caption='提示：',style=wx.OK)

    def OnNewClick( self, event ):
        self.m_textCtrl1.SetValue('')
        self.m_textCtrl2.SetValue('0')
        self.m_textCtrl3.SetValue('90')

    def OnDiscountEnter( self, event ):
        self.dis_rate = float(self.m_textCtrl3.GetValue())
        if self.dis_rate>100 or self.dis_rate<0:
            wx.MessageBox('折扣应设置在0-100之内！', caption='提示：',style=wx.OK)
        else:
            self.discount = round(self.dis_rate * self.floCharge / 100,2)
            self.m_staticText11.Label = '折扣后收费：%s元' % self.discount

    def OnCalClick( self, event ):
        self.OnGoalEnter(None)
        self.OnDiscountEnter(None)

    def OnSaveClick( self, event ):
        self.OnCalClick(None)
        self.name = self.m_textCtrl1.GetValue()
        if self.name=='':
            wx.MessageBox('请填写项目名称！', caption='提示：',style=wx.OK)
            return
        temp_record = calRecord(self.index,self.name,self.type, self.floGoal, self.floCharge, self.dis_rate, self.discount)
        self.collect.append(temp_record)
        self.m_listBox2.Append('%s、[%s%%] %s元 [%s]' % (self.index,self.dis_rate,self.discount,self.name))
        self.index +=1

    def OnListClick( self, event ):
        if len(self.m_listBox2.GetSelections())>0:
            self.total_charge = 0
            for index in self.m_listBox2.GetSelections():
                num_index = int(self.m_listBox2.GetString(index).split('、',1)[0])
                for item in self.collect:
                    if num_index==item.getIndex():
                        self.total_charge = self.total_charge + item.getDiscount()
            self.total_charge = round(self.total_charge * float(self.m_textCtrl5.GetValue())/100,2)
        else:
            self.total_charge = 0
        self.m_staticText18.Label = '总价：%s元' % self.total_charge
        
    def OnCopyClick( self, event ):
        pyperclip.copy(self.m_textCtrl4.GetValue())

    def OnClearClick( self, event ):
        self.m_textCtrl4.SetValue( '项目招标代理服务费计算表\n==================\n')

    def OnSumDiscountEnter( self, event ):
        self.OnListClick(None)
        
    def OnDeleteClick( self, event ):
        if len(self.m_listBox2.GetSelections())==0:
            wx.MessageBox('请选择删除项目！', caption='提示：',style=wx.OK)
        else:
            for index in reversed(self.m_listBox2.GetSelections()):
                self.m_listBox2.Delete(index)

    def OnOutputClick( self, event ):
        self.OnListClick(None)
        self.OnClearClick(None)
        if len(self.m_listBox2.GetSelections())==0:
            wx.MessageBox('请选择生成报表的项目！', caption='提示：',style=wx.OK)
        else:
            str_article = ''
            for index in self.m_listBox2.GetSelections():
                num_index = int(self.m_listBox2.GetString(index).split('、',1)[0])
                for item in self.collect:
                    if num_index==item.getIndex():
                        str_article = str_article + item.getWord()
            str_article = str_article + '总折扣：%s%%，总费用为：%s元' % (self.m_textCtrl5.GetValue(),self.total_charge)
            self.m_textCtrl4.SetValue(self.m_textCtrl4.GetValue()+str_article)

if __name__ == '__main__':
    app = wx.App()
    login_frame = loadCalFrame(None)
    login_frame.Show(True)
    app.MainLoop()
